/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedOperatorsIndexRouteImport } from './routes/_authenticated/operators/index'
import { Route as AuthenticatedOperatorIndexRouteImport } from './routes/_authenticated/operator.index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedOperatorsIdRouteImport } from './routes/_authenticated/operators/$id'
import { Route as AuthenticatedOperatorTicketsRouteImport } from './routes/_authenticated/operator.tickets'
import { Route as AuthenticatedOperatorProfileRouteImport } from './routes/_authenticated/operator.profile'
import { Route as AuthenticatedOperatorPrestartRouteImport } from './routes/_authenticated/operator.prestart'
import { Route as AuthenticatedOperatorPhotosRouteImport } from './routes/_authenticated/operator.photos'
import { Route as AuthenticatedOperatorHoursRouteImport } from './routes/_authenticated/operator.hours'
import { Route as AuthenticatedOperatorDefectRouteImport } from './routes/_authenticated/operator.defect'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets/$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksCheckExpiriesRouteImport } from './routes/api/public/hooks/check-expiries'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorsIndexRoute =
  AuthenticatedOperatorsIndexRouteImport.update({
    id: '/operators/',
    path: '/operators/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorIndexRoute =
  AuthenticatedOperatorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorsIdRoute =
  AuthenticatedOperatorsIdRouteImport.update({
    id: '/operators/$id',
    path: '/operators/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorTicketsRoute =
  AuthenticatedOperatorTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorProfileRoute =
  AuthenticatedOperatorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorPrestartRoute =
  AuthenticatedOperatorPrestartRouteImport.update({
    id: '/prestart',
    path: '/prestart',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorPhotosRoute =
  AuthenticatedOperatorPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorHoursRoute =
  AuthenticatedOperatorHoursRouteImport.update({
    id: '/hours',
    path: '/hours',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorDefectRoute =
  AuthenticatedOperatorDefectRouteImport.update({
    id: '/defect',
    path: '/defect',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckExpiriesRoute =
  ApiPublicHooksCheckExpiriesRouteImport.update({
    id: '/api/public/hooks/check-expiries',
    path: '/api/public/hooks/check-expiries',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operator': typeof AuthenticatedOperatorRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/operator/defect': typeof AuthenticatedOperatorDefectRoute
  '/operator/hours': typeof AuthenticatedOperatorHoursRoute
  '/operator/photos': typeof AuthenticatedOperatorPhotosRoute
  '/operator/prestart': typeof AuthenticatedOperatorPrestartRoute
  '/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/operator/tickets': typeof AuthenticatedOperatorTicketsRoute
  '/operators/$id': typeof AuthenticatedOperatorsIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/operator/': typeof AuthenticatedOperatorIndexRoute
  '/operators/': typeof AuthenticatedOperatorsIndexRoute
  '/api/public/hooks/check-expiries': typeof ApiPublicHooksCheckExpiriesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/operator/defect': typeof AuthenticatedOperatorDefectRoute
  '/operator/hours': typeof AuthenticatedOperatorHoursRoute
  '/operator/photos': typeof AuthenticatedOperatorPhotosRoute
  '/operator/prestart': typeof AuthenticatedOperatorPrestartRoute
  '/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/operator/tickets': typeof AuthenticatedOperatorTicketsRoute
  '/operators/$id': typeof AuthenticatedOperatorsIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/operator': typeof AuthenticatedOperatorIndexRoute
  '/operators': typeof AuthenticatedOperatorsIndexRoute
  '/api/public/hooks/check-expiries': typeof ApiPublicHooksCheckExpiriesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/operator/defect': typeof AuthenticatedOperatorDefectRoute
  '/_authenticated/operator/hours': typeof AuthenticatedOperatorHoursRoute
  '/_authenticated/operator/photos': typeof AuthenticatedOperatorPhotosRoute
  '/_authenticated/operator/prestart': typeof AuthenticatedOperatorPrestartRoute
  '/_authenticated/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/_authenticated/operator/tickets': typeof AuthenticatedOperatorTicketsRoute
  '/_authenticated/operators/$id': typeof AuthenticatedOperatorsIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/operator/': typeof AuthenticatedOperatorIndexRoute
  '/_authenticated/operators/': typeof AuthenticatedOperatorsIndexRoute
  '/api/public/hooks/check-expiries': typeof ApiPublicHooksCheckExpiriesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/onboarding'
    | '/operator'
    | '/reports'
    | '/settings'
    | '/team'
    | '/assets/$id'
    | '/operator/defect'
    | '/operator/hours'
    | '/operator/photos'
    | '/operator/prestart'
    | '/operator/profile'
    | '/operator/tickets'
    | '/operators/$id'
    | '/assets/'
    | '/operator/'
    | '/operators/'
    | '/api/public/hooks/check-expiries'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/team'
    | '/assets/$id'
    | '/operator/defect'
    | '/operator/hours'
    | '/operator/photos'
    | '/operator/prestart'
    | '/operator/profile'
    | '/operator/tickets'
    | '/operators/$id'
    | '/assets'
    | '/operator'
    | '/operators'
    | '/api/public/hooks/check-expiries'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/operator'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/assets/$id'
    | '/_authenticated/operator/defect'
    | '/_authenticated/operator/hours'
    | '/_authenticated/operator/photos'
    | '/_authenticated/operator/prestart'
    | '/_authenticated/operator/profile'
    | '/_authenticated/operator/tickets'
    | '/_authenticated/operators/$id'
    | '/_authenticated/assets/'
    | '/_authenticated/operator/'
    | '/_authenticated/operators/'
    | '/api/public/hooks/check-expiries'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksCheckExpiriesRoute: typeof ApiPublicHooksCheckExpiriesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operators/': {
      id: '/_authenticated/operators/'
      path: '/operators'
      fullPath: '/operators/'
      preLoaderRoute: typeof AuthenticatedOperatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/': {
      id: '/_authenticated/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof AuthenticatedOperatorIndexRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operators/$id': {
      id: '/_authenticated/operators/$id'
      path: '/operators/$id'
      fullPath: '/operators/$id'
      preLoaderRoute: typeof AuthenticatedOperatorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/tickets': {
      id: '/_authenticated/operator/tickets'
      path: '/tickets'
      fullPath: '/operator/tickets'
      preLoaderRoute: typeof AuthenticatedOperatorTicketsRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/profile': {
      id: '/_authenticated/operator/profile'
      path: '/profile'
      fullPath: '/operator/profile'
      preLoaderRoute: typeof AuthenticatedOperatorProfileRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/prestart': {
      id: '/_authenticated/operator/prestart'
      path: '/prestart'
      fullPath: '/operator/prestart'
      preLoaderRoute: typeof AuthenticatedOperatorPrestartRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/photos': {
      id: '/_authenticated/operator/photos'
      path: '/photos'
      fullPath: '/operator/photos'
      preLoaderRoute: typeof AuthenticatedOperatorPhotosRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/hours': {
      id: '/_authenticated/operator/hours'
      path: '/hours'
      fullPath: '/operator/hours'
      preLoaderRoute: typeof AuthenticatedOperatorHoursRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/defect': {
      id: '/_authenticated/operator/defect'
      path: '/defect'
      fullPath: '/operator/defect'
      preLoaderRoute: typeof AuthenticatedOperatorDefectRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-expiries': {
      id: '/api/public/hooks/check-expiries'
      path: '/api/public/hooks/check-expiries'
      fullPath: '/api/public/hooks/check-expiries'
      preLoaderRoute: typeof ApiPublicHooksCheckExpiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOperatorRouteChildren {
  AuthenticatedOperatorDefectRoute: typeof AuthenticatedOperatorDefectRoute
  AuthenticatedOperatorHoursRoute: typeof AuthenticatedOperatorHoursRoute
  AuthenticatedOperatorPhotosRoute: typeof AuthenticatedOperatorPhotosRoute
  AuthenticatedOperatorPrestartRoute: typeof AuthenticatedOperatorPrestartRoute
  AuthenticatedOperatorProfileRoute: typeof AuthenticatedOperatorProfileRoute
  AuthenticatedOperatorTicketsRoute: typeof AuthenticatedOperatorTicketsRoute
  AuthenticatedOperatorIndexRoute: typeof AuthenticatedOperatorIndexRoute
}

const AuthenticatedOperatorRouteChildren: AuthenticatedOperatorRouteChildren = {
  AuthenticatedOperatorDefectRoute: AuthenticatedOperatorDefectRoute,
  AuthenticatedOperatorHoursRoute: AuthenticatedOperatorHoursRoute,
  AuthenticatedOperatorPhotosRoute: AuthenticatedOperatorPhotosRoute,
  AuthenticatedOperatorPrestartRoute: AuthenticatedOperatorPrestartRoute,
  AuthenticatedOperatorProfileRoute: AuthenticatedOperatorProfileRoute,
  AuthenticatedOperatorTicketsRoute: AuthenticatedOperatorTicketsRoute,
  AuthenticatedOperatorIndexRoute: AuthenticatedOperatorIndexRoute,
}

const AuthenticatedOperatorRouteWithChildren =
  AuthenticatedOperatorRoute._addFileChildren(
    AuthenticatedOperatorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedOperatorsIdRoute: typeof AuthenticatedOperatorsIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedOperatorsIndexRoute: typeof AuthenticatedOperatorsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedOperatorsIdRoute: AuthenticatedOperatorsIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedOperatorsIndexRoute: AuthenticatedOperatorsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksCheckExpiriesRoute: ApiPublicHooksCheckExpiriesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
