/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIdRouteImport } from './routes/m.$id'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedOperatorsIndexRouteImport } from './routes/_authenticated/operators/index'
import { Route as AuthenticatedOperatorIndexRouteImport } from './routes/_authenticated/operator.index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AuthenticatedOperatorsIdRouteImport } from './routes/_authenticated/operators/$id'
import { Route as AuthenticatedOperatorTicketsRouteImport } from './routes/_authenticated/operator.tickets'
import { Route as AuthenticatedOperatorProfileRouteImport } from './routes/_authenticated/operator.profile'
import { Route as AuthenticatedOperatorPrestartRouteImport } from './routes/_authenticated/operator.prestart'
import { Route as AuthenticatedOperatorPhotosRouteImport } from './routes/_authenticated/operator.photos'
import { Route as AuthenticatedOperatorHoursRouteImport } from './routes/_authenticated/operator.hours'
import { Route as AuthenticatedOperatorDocumentsRouteImport } from './routes/_authenticated/operator.documents'
import { Route as AuthenticatedOperatorDefectRouteImport } from './routes/_authenticated/operator.defect'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets/$id'
import { Route as AuthenticatedAdminPrestartsRouteImport } from './routes/_authenticated/admin.prestarts'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksCheckExpiriesRouteImport } from './routes/api/public/hooks/check-expiries'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIdRoute = MIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorsIndexRoute =
  AuthenticatedOperatorsIndexRouteImport.update({
    id: '/operators/',
    path: '/operators/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorIndexRoute =
  AuthenticatedOperatorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperatorsIdRoute =
  AuthenticatedOperatorsIdRouteImport.update({
    id: '/operators/$id',
    path: '/operators/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorTicketsRoute =
  AuthenticatedOperatorTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorProfileRoute =
  AuthenticatedOperatorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorPrestartRoute =
  AuthenticatedOperatorPrestartRouteImport.update({
    id: '/prestart',
    path: '/prestart',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorPhotosRoute =
  AuthenticatedOperatorPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorHoursRoute =
  AuthenticatedOperatorHoursRouteImport.update({
    id: '/hours',
    path: '/hours',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorDocumentsRoute =
  AuthenticatedOperatorDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedOperatorDefectRoute =
  AuthenticatedOperatorDefectRouteImport.update({
    id: '/defect',
    path: '/defect',
    getParentRoute: () => AuthenticatedOperatorRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPrestartsRoute =
  AuthenticatedAdminPrestartsRouteImport.update({
    id: '/admin/prestarts',
    path: '/admin/prestarts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/admin/enquiries',
    path: '/admin/enquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckExpiriesRoute =
  ApiPublicHooksCheckExpiriesRouteImport.update({
    id: '/api/public/hooks/check-expiries',
    path: '/api/public/hooks/check-expiries',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operator': typeof AuthenticatedOperatorRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/join/$code': typeof JoinCodeRoute
  '/m/$id': typeof MIdRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/prestarts': typeof AuthenticatedAdminPrestartsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/operator/defect': typeof AuthenticatedOperatorDefectRoute
  '/operator/documents': typeof AuthenticatedOperatorDocumentsRoute
  '/operator/hours': typeof AuthenticatedOperatorHoursRoute
  '/operator/photos': typeof AuthenticatedOperatorPhotosRoute
  '/operator/prestart': typeof AuthenticatedOperatorPrestartRoute
  '/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/operator/tickets': typeof AuthenticatedOperatorTicketsRoute
  '/operators/$id': typeof AuthenticatedOperatorsIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/operator/': typeof AuthenticatedOperatorIndexRoute
  '/operators/': typeof AuthenticatedOperatorsIndexRoute
  '/api/public/hooks/check-expiries': typeof ApiPublicHooksCheckExpiriesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/join/$code': typeof JoinCodeRoute
  '/m/$id': typeof MIdRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/prestarts': typeof AuthenticatedAdminPrestartsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/operator/defect': typeof AuthenticatedOperatorDefectRoute
  '/operator/documents': typeof AuthenticatedOperatorDocumentsRoute
  '/operator/hours': typeof AuthenticatedOperatorHoursRoute
  '/operator/photos': typeof AuthenticatedOperatorPhotosRoute
  '/operator/prestart': typeof AuthenticatedOperatorPrestartRoute
  '/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/operator/tickets': typeof AuthenticatedOperatorTicketsRoute
  '/operators/$id': typeof AuthenticatedOperatorsIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/operator': typeof AuthenticatedOperatorIndexRoute
  '/operators': typeof AuthenticatedOperatorsIndexRoute
  '/api/public/hooks/check-expiries': typeof ApiPublicHooksCheckExpiriesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/join/$code': typeof JoinCodeRoute
  '/m/$id': typeof MIdRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/prestarts': typeof AuthenticatedAdminPrestartsRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/operator/defect': typeof AuthenticatedOperatorDefectRoute
  '/_authenticated/operator/documents': typeof AuthenticatedOperatorDocumentsRoute
  '/_authenticated/operator/hours': typeof AuthenticatedOperatorHoursRoute
  '/_authenticated/operator/photos': typeof AuthenticatedOperatorPhotosRoute
  '/_authenticated/operator/prestart': typeof AuthenticatedOperatorPrestartRoute
  '/_authenticated/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/_authenticated/operator/tickets': typeof AuthenticatedOperatorTicketsRoute
  '/_authenticated/operators/$id': typeof AuthenticatedOperatorsIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/operator/': typeof AuthenticatedOperatorIndexRoute
  '/_authenticated/operators/': typeof AuthenticatedOperatorsIndexRoute
  '/api/public/hooks/check-expiries': typeof ApiPublicHooksCheckExpiriesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/unsubscribe'
    | '/billing'
    | '/dashboard'
    | '/onboarding'
    | '/operator'
    | '/reports'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/email/unsubscribe'
    | '/join/$code'
    | '/m/$id'
    | '/admin/enquiries'
    | '/admin/prestarts'
    | '/assets/$id'
    | '/operator/defect'
    | '/operator/documents'
    | '/operator/hours'
    | '/operator/photos'
    | '/operator/prestart'
    | '/operator/profile'
    | '/operator/tickets'
    | '/operators/$id'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/assets/'
    | '/operator/'
    | '/operators/'
    | '/api/public/hooks/check-expiries'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/unsubscribe'
    | '/billing'
    | '/dashboard'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/email/unsubscribe'
    | '/join/$code'
    | '/m/$id'
    | '/admin/enquiries'
    | '/admin/prestarts'
    | '/assets/$id'
    | '/operator/defect'
    | '/operator/documents'
    | '/operator/hours'
    | '/operator/photos'
    | '/operator/prestart'
    | '/operator/profile'
    | '/operator/tickets'
    | '/operators/$id'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/assets'
    | '/operator'
    | '/operators'
    | '/api/public/hooks/check-expiries'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/operator'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/tickets'
    | '/email/unsubscribe'
    | '/join/$code'
    | '/m/$id'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/prestarts'
    | '/_authenticated/assets/$id'
    | '/_authenticated/operator/defect'
    | '/_authenticated/operator/documents'
    | '/_authenticated/operator/hours'
    | '/_authenticated/operator/photos'
    | '/_authenticated/operator/prestart'
    | '/_authenticated/operator/profile'
    | '/_authenticated/operator/tickets'
    | '/_authenticated/operators/$id'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/_authenticated/assets/'
    | '/_authenticated/operator/'
    | '/_authenticated/operators/'
    | '/api/public/hooks/check-expiries'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  JoinCodeRoute: typeof JoinCodeRoute
  MIdRoute: typeof MIdRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCheckExpiriesRoute: typeof ApiPublicHooksCheckExpiriesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$id': {
      id: '/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operators/': {
      id: '/_authenticated/operators/'
      path: '/operators'
      fullPath: '/operators/'
      preLoaderRoute: typeof AuthenticatedOperatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/': {
      id: '/_authenticated/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof AuthenticatedOperatorIndexRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operators/$id': {
      id: '/_authenticated/operators/$id'
      path: '/operators/$id'
      fullPath: '/operators/$id'
      preLoaderRoute: typeof AuthenticatedOperatorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/tickets': {
      id: '/_authenticated/operator/tickets'
      path: '/tickets'
      fullPath: '/operator/tickets'
      preLoaderRoute: typeof AuthenticatedOperatorTicketsRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/profile': {
      id: '/_authenticated/operator/profile'
      path: '/profile'
      fullPath: '/operator/profile'
      preLoaderRoute: typeof AuthenticatedOperatorProfileRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/prestart': {
      id: '/_authenticated/operator/prestart'
      path: '/prestart'
      fullPath: '/operator/prestart'
      preLoaderRoute: typeof AuthenticatedOperatorPrestartRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/photos': {
      id: '/_authenticated/operator/photos'
      path: '/photos'
      fullPath: '/operator/photos'
      preLoaderRoute: typeof AuthenticatedOperatorPhotosRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/hours': {
      id: '/_authenticated/operator/hours'
      path: '/hours'
      fullPath: '/operator/hours'
      preLoaderRoute: typeof AuthenticatedOperatorHoursRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/documents': {
      id: '/_authenticated/operator/documents'
      path: '/documents'
      fullPath: '/operator/documents'
      preLoaderRoute: typeof AuthenticatedOperatorDocumentsRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/operator/defect': {
      id: '/_authenticated/operator/defect'
      path: '/defect'
      fullPath: '/operator/defect'
      preLoaderRoute: typeof AuthenticatedOperatorDefectRouteImport
      parentRoute: typeof AuthenticatedOperatorRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/prestarts': {
      id: '/_authenticated/admin/prestarts'
      path: '/admin/prestarts'
      fullPath: '/admin/prestarts'
      preLoaderRoute: typeof AuthenticatedAdminPrestartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-expiries': {
      id: '/api/public/hooks/check-expiries'
      path: '/api/public/hooks/check-expiries'
      fullPath: '/api/public/hooks/check-expiries'
      preLoaderRoute: typeof ApiPublicHooksCheckExpiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOperatorRouteChildren {
  AuthenticatedOperatorDefectRoute: typeof AuthenticatedOperatorDefectRoute
  AuthenticatedOperatorDocumentsRoute: typeof AuthenticatedOperatorDocumentsRoute
  AuthenticatedOperatorHoursRoute: typeof AuthenticatedOperatorHoursRoute
  AuthenticatedOperatorPhotosRoute: typeof AuthenticatedOperatorPhotosRoute
  AuthenticatedOperatorPrestartRoute: typeof AuthenticatedOperatorPrestartRoute
  AuthenticatedOperatorProfileRoute: typeof AuthenticatedOperatorProfileRoute
  AuthenticatedOperatorTicketsRoute: typeof AuthenticatedOperatorTicketsRoute
  AuthenticatedOperatorIndexRoute: typeof AuthenticatedOperatorIndexRoute
}

const AuthenticatedOperatorRouteChildren: AuthenticatedOperatorRouteChildren = {
  AuthenticatedOperatorDefectRoute: AuthenticatedOperatorDefectRoute,
  AuthenticatedOperatorDocumentsRoute: AuthenticatedOperatorDocumentsRoute,
  AuthenticatedOperatorHoursRoute: AuthenticatedOperatorHoursRoute,
  AuthenticatedOperatorPhotosRoute: AuthenticatedOperatorPhotosRoute,
  AuthenticatedOperatorPrestartRoute: AuthenticatedOperatorPrestartRoute,
  AuthenticatedOperatorProfileRoute: AuthenticatedOperatorProfileRoute,
  AuthenticatedOperatorTicketsRoute: AuthenticatedOperatorTicketsRoute,
  AuthenticatedOperatorIndexRoute: AuthenticatedOperatorIndexRoute,
}

const AuthenticatedOperatorRouteWithChildren =
  AuthenticatedOperatorRoute._addFileChildren(
    AuthenticatedOperatorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminPrestartsRoute: typeof AuthenticatedAdminPrestartsRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedOperatorsIdRoute: typeof AuthenticatedOperatorsIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedOperatorsIndexRoute: typeof AuthenticatedOperatorsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminPrestartsRoute: AuthenticatedAdminPrestartsRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedOperatorsIdRoute: AuthenticatedOperatorsIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedOperatorsIndexRoute: AuthenticatedOperatorsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  JoinCodeRoute: JoinCodeRoute,
  MIdRoute: MIdRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCheckExpiriesRoute: ApiPublicHooksCheckExpiriesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
